✨ Added free IBM hardware (``kyiv``, ``brisbane``, ``sherbrooke``) to CLI
munich-quantum-toolkit/bench pull request #381
Opened 2024-09-19 13:02 UTC by Drewniok

This PR adds the free IBM quantum computers (``kyiv``, ``brisbane``, ``sherbrooke``) to the CLI of MQT-Bench.
We also provide a script that generates the calibration files for IBM devices based on the calibration csv files downloaded from IBM.

2024-09-22 14:48 UTC, burgholzer requested changes
Thanks for working on this! 🙏🏼 
Sorry that it took a while to review.
Most of the comments you'll find below are rather on the high-level side and are probably better translated to follow-up issues.
I think my biggest concern that should probably be addressed here is the amount of code duplication between the IBM providers.

2024-09-22 14:48 UTC, burgholzer commented on utils/requirements.txt
I am not the biggest fan of adding random `requirements.txt` files throughout the repository for purposes like these. The "modern" way to incorporate such extra functionality would be to use dedicated "extra" dependencies in the `pyproject.toml` or to use https://peps.python.org/pep-0723 if it is really just dependencies for a script. See for example https://docs.astral.sh/uv/guides/scripts/#running-a-script-with-dependencies
Given that this is a script that really doesn't need more than that, I would follow the above guide and turn this into inline metadata for the script.

Note that `qiskit_ibm_runtime` is a direct requirement of `pytket_qiskit`. So it would be directly available within mqt-bench. However, this one-off script makes much more sense in a separate directory as compared to in the package.

2024-09-22 14:48 UTC, burgholzer commented on utils/ibm_csv_to_mqt_json.py
I'd have a slight preference for calling the containing folder `scripts` compared to `utils`. Really not a big fan of the term `utils` 🙃

2024-09-23 05:40 UTC, Drewniok commented
> Thanks for working on this! 🙏🏼 Sorry that it took a while to review. Most of the comments you'll find below are rather on the high-level side and are probably better translated to follow-up issues. I think my biggest concern that should probably be addressed here is the amount of code duplication between the IBM providers.

Many thanks @burgholzer for your review! That's super helpful! And I totally agree about the code duplication! I'll address that asap.

2024-09-25 12:01 UTC, Drewniok commented on src/mqt/bench/calibration_files/ibm_brisbane_calibration.json
Thanks again @burgholzer for your comments! 
This is the information we get from IBM: 
 
``"Qubit","T1 (us)","T2 (us)","Frequency (GHz)","Anharmonicity (GHz)","Readout assignment error ","Prob meas0 prep1 ","Prob meas1 prep0 ","Readout length (ns)","ID error ","Z-axis rotation (rz) error ","√x (sx) error ","Pauli-X error ","ECR error ","Gate time (ns)","Operational"`` 

Which column collects the timing information?

2024-09-25 12:04 UTC, Drewniok commented on utils/ibm_csv_to_mqt_json.py
sounds good to me!

2024-09-25 13:00 UTC, burgholzer commented on src/mqt/bench/calibration_files/ibm_brisbane_calibration.json
Based on the `ibm_csv_to_mqt_json.py` script, you do have access to quite a lot more information. The `backend.target` property (https://github.com/Qiskit/qiskit-ibm-runtime/blob/fd2d7c0db65a438b6324b04ebacbb75d793148b1/qiskit_ibm_runtime/ibm_backend.py#L338) contains all the information you could ever want or need one the device (see https://github.com/Qiskit/qiskit/blob/dcd41e9fcedd6f51fe725c25c4ed583c22bb3525/qiskit/transpiler/target.py#L164).
That includes gate durations and error rates for all of the gates a device supports.

Side note: it the name of the script really that appropriate? it doesn't really take a CSV file but rather a backend and converts it to the standardized format AFAICT.

2024-09-25 13:08 UTC, Drewniok commented on src/mqt/bench/calibration_files/ibm_brisbane_calibration.json
Thank you very much! I'll take a look at it!

Hmm, I am not sure I understand your concern. The input for ``ibm_csv_to_mqt_json`` is the csv file downloaded from IBM. But of course we can change the name!

2024-09-25 16:13 UTC, Drewniok commented on src/mqt/bench/calibration_files/ibm_brisbane_calibration.json
ah, that's a good point! I already extract the ``coupling_map`` and the base gates from the backend in the script, but I did not find that the other information can be accessed as well. Thank you very much!

2024-09-26 11:40 UTC, Drewniok commented on utils/requirements.txt
@burgholzer wow! Many thanks for this information. That's so cool! Love it!

2024-10-06 15:37 UTC, Drewniok commented
@burgholzer Just a small update: I have not forgotten about this and will try to finish it asap!

2024-10-16 19:29 UTC, Drewniok commented
@burgholzer We need to add a secret to add the token for QiskitRuntimeService.

2025-05-05 11:55 UTC, nquetschlich commented
This PR is closed for now due to the recent other PRs and changes in MQT Bench. The mentioned devices might be added in the future in a different PR.

2025-05-05 11:55 UTC, closed without merging